#Q2
SELECT PRODUCT_ORDER.OrderID, COUNT(PRODUCT_ORDER.OrderID) AS Total_Product, SUM(Product.Cost) AS Total_cost 
FROM PRODUCT_ORDER
LEFT JOIN PRODUCT
ON PRODUCT_ORDER.ProductID=PRODUCT.ProductID 
GROUP BY PRODUCT_ORDER.OrderID 
ORDER BY Total_cost 
DESC LIMIT 10;

#Q1
SELECT t.OrderID, ORDER_.PlacedDate, t.Total_cost FROM 
(SELECT PRODUCT_ORDER.OrderID, COUNT(PRODUCT_ORDER.OrderID) AS Total_Product, SUM(Product.Cost) AS Total_cost
FROM PRODUCT_ORDER
LEFT JOIN PRODUCT
ON PRODUCT_ORDER.ProductID=PRODUCT.ProductID 
GROUP BY PRODUCT_ORDER.OrderID) AS t
LEFT JOIN Order_
ON
t.OrderID=Order_.OrderID ORDER BY ORDER_.PlacedDate;

#Q3
SELECT t.OrderID, t.PlacedDate, t.State FROM
(SELECT ORDER_.OrderID,ORDER_.PlacedDate,PRODUCT_ORDER.State FROM ORDER_
LEFT JOIN PRODUCT_ORDER
ON ORDER_.OrderID = PRODUCT_ORDER.OrderID) AS t
WHERE t.State LIKE '%Order Placed%'
AND
t.PlacedDate < '2018-01-13'
limit 20;

#Q4

SELECT ORDER_.OrderID, ORDER_.PlacedDate FROM ORDER_
RIGHT JOIN SHOPPER
ON ORDER_.ShopperID = SHOPPER.ShopperID
WHERE ORDER_.PlacedDate between CURRENT_DATE - INTERVAL '2' MONTH AND CURRENT_DATE;


#Q5
SELECT SHOPPER.ShopperID, ORDER_.OrderID, ORDER_.PlacedDate FROM ORDER_
RIGHT JOIN SHOPPER
ON ORDER_.ShopperID = SHOPPER.ShopperID
WHERE ORDER_.PlacedDate between CURRENT_DATE - INTERVAL '15' DAY AND CURRENT_DATE;

#Q6

SELECT u.OrderID, u.state, PRODUCT.ProductID, PRODUCT.Name
FROM(
SELECT t.OrderID, t.PlacedDate, t.State, t.ProductID FROM
(SELECT ORDER_.OrderID,ORDER_.PlacedDate,PRODUCT_ORDER.State, PRODUCT_ORDER.ProductID  FROM ORDER_
LEFT JOIN PRODUCT_ORDER
ON ORDER_.OrderID = PRODUCT_ORDER.OrderID) AS t
WHERE t.State LIKE '%Shipped%')as u
LEFT JOIN PRODUCT
ON
u.ProductID = PRODUCT.ProductID
WHERE u.OrderID = 2;


#Q7

SELECT u.OrderID, u.state, PRODUCT.ProductID, PRODUCT.Name, PRODUCT.Cost
FROM(
SELECT t.OrderID, t.PlacedDate, t.State, t.ProductID FROM
(SELECT ORDER_.OrderID,ORDER_.PlacedDate,PRODUCT_ORDER.State, PRODUCT_ORDER.ProductID  FROM ORDER_
LEFT JOIN PRODUCT_ORDER
ON ORDER_.OrderID = PRODUCT_ORDER.OrderID) AS t
)as u
LEFT JOIN PRODUCT
ON
u.ProductID = PRODUCT.ProductID
WHERE PRODUCT.Cost > 30 AND PRODUCT.Cost < 250;

#Q8

UPDATE PRODUCT_ORDER 
INNER JOIN ORDER_ ON PRODUCT_ORDER.OrderID=ORDER_.OrderID
SET PRODUCT_ORDER.State = 'Shipped'
WHERE ORDER_.PlacedDate = '2018-12-03';



SELECT PRODUCT_ORDER.OrderID, PRODUCT_ORDER.State FROM PRODUCT_ORDER 
INNER JOIN ORDER_ 
ON PRODUCT_ORDER.OrderID=ORDER_.OrderID
WHERE ORDER_.PlacedDate = '2018-12-03';
